"""virtual key hardening: store a hash instead of the raw secret

Before this revision, `virtual_keys.virtual_key` stored the raw bearer token
in plaintext, and four other tables (`request_logs`, `cache_entries`,
`rate_limit_windows`, `usage_records`) copied that same plaintext value as
their tenant-reference column - so the live secret was duplicated into every
request log and cache row. This revision replaces the plaintext column with
a one-way `key_hash` (+ a `key_prefix` for display only) on `virtual_keys`,
and replaces the four dependent tables' string column with an integer FK to
`virtual_keys.id`, which carries no secret at all.

Hand-written, not autogenerated: this needs a data backfill (hash the
existing plaintext, look up/join the owning key), not just a schema diff.

downgrade() restores the old column shapes but CANNOT restore the original
plaintext for self-serve-issued keys - hashing is one-way by design. Only
the seeded demo tenants are recoverable, by re-running seed.py against
data/seed_keys.json after downgrading.

Revision ID: 0002
Revises: 0001
Create Date: 2026-08-19
"""

import hashlib
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

revision: str = "0002"
down_revision: Union[str, None] = "0001"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def _hash(raw: str) -> str:
    return hashlib.sha256(raw.encode()).hexdigest()


def upgrade() -> None:
    conn = op.get_bind()

    # --- virtual_keys: plaintext -> key_hash + key_prefix ---
    op.add_column("virtual_keys", sa.Column("key_hash", sa.String(), nullable=True))
    op.add_column("virtual_keys", sa.Column("key_prefix", sa.String(), nullable=True))
    for row in conn.execute(sa.text("SELECT id, virtual_key FROM virtual_keys")):
        conn.execute(
            sa.text("UPDATE virtual_keys SET key_hash = :h, key_prefix = :p WHERE id = :id"),
            {"h": _hash(row.virtual_key), "p": row.virtual_key[:12], "id": row.id},
        )
    op.alter_column("virtual_keys", "key_hash", nullable=False)
    op.alter_column("virtual_keys", "key_prefix", nullable=False)
    op.drop_index("ix_virtual_keys_virtual_key", table_name="virtual_keys")
    op.drop_column("virtual_keys", "virtual_key")
    op.create_index("ix_virtual_keys_key_hash", "virtual_keys", ["key_hash"], unique=True)

    key_id_by_hash = {
        h: id_
        for id_, h in conn.execute(sa.text("SELECT id, key_hash FROM virtual_keys"))
    }

    def _lookup(raw: str) -> int | None:
        return key_id_by_hash.get(_hash(raw))

    # --- request_logs: nullable FK - "rejected_auth" rows never resolve to a
    # known key (see routers/chat.py::_log_rejection's "" default), so this
    # column can't be NOT NULL the way cache_entries' can. ---
    op.add_column("request_logs", sa.Column("virtual_key_id", sa.Integer(), nullable=True))
    for row in conn.execute(sa.text("SELECT DISTINCT virtual_key FROM request_logs")):
        key_id = _lookup(row.virtual_key) if row.virtual_key else None
        if key_id is not None:
            conn.execute(
                sa.text(
                    "UPDATE request_logs SET virtual_key_id = :kid WHERE virtual_key = :vk"
                ),
                {"kid": key_id, "vk": row.virtual_key},
            )
    op.drop_index("ix_request_logs_virtual_key", table_name="request_logs")
    op.drop_column("request_logs", "virtual_key")
    op.create_foreign_key(
        "fk_request_logs_virtual_key_id", "request_logs", "virtual_keys", ["virtual_key_id"], ["id"]
    )
    op.create_index("ix_request_logs_virtual_key_id", "request_logs", ["virtual_key_id"])

    # --- cache_entries: always tied to a real key -> NOT NULL FK ---
    op.add_column("cache_entries", sa.Column("virtual_key_id", sa.Integer(), nullable=True))
    for row in conn.execute(sa.text("SELECT DISTINCT virtual_key FROM cache_entries")):
        key_id = _lookup(row.virtual_key)
        if key_id is not None:
            conn.execute(
                sa.text(
                    "UPDATE cache_entries SET virtual_key_id = :kid WHERE virtual_key = :vk"
                ),
                {"kid": key_id, "vk": row.virtual_key},
            )
    op.drop_index("ix_cache_entries_virtual_key", table_name="cache_entries")
    op.drop_column("cache_entries", "virtual_key")
    # Orphaned rows (a cache entry whose owning key no longer exists) can't
    # get a valid FK value - drop them rather than leave the column nullable,
    # matching the rate_limit_windows/usage_records treatment below.
    op.execute("DELETE FROM cache_entries WHERE virtual_key_id IS NULL")
    op.alter_column("cache_entries", "virtual_key_id", nullable=False)
    op.create_foreign_key(
        "fk_cache_entries_virtual_key_id", "cache_entries", "virtual_keys", ["virtual_key_id"], ["id"]
    )
    op.create_index("ix_cache_entries_virtual_key_id", "cache_entries", ["virtual_key_id"])

    # --- rate_limit_windows: composite PK (virtual_key, window_start) ---
    op.add_column("rate_limit_windows", sa.Column("virtual_key_id", sa.Integer(), nullable=True))
    for row in conn.execute(sa.text("SELECT DISTINCT virtual_key FROM rate_limit_windows")):
        key_id = _lookup(row.virtual_key)
        if key_id is not None:
            conn.execute(
                sa.text(
                    "UPDATE rate_limit_windows SET virtual_key_id = :kid WHERE virtual_key = :vk"
                ),
                {"kid": key_id, "vk": row.virtual_key},
            )
    op.execute("DELETE FROM rate_limit_windows WHERE virtual_key_id IS NULL")
    op.drop_constraint("rate_limit_windows_pkey", "rate_limit_windows", type_="primary")
    op.drop_column("rate_limit_windows", "virtual_key")
    op.alter_column("rate_limit_windows", "virtual_key_id", nullable=False)
    op.create_primary_key(
        "pk_rate_limit_windows", "rate_limit_windows", ["virtual_key_id", "window_start"]
    )
    op.create_foreign_key(
        "fk_rate_limit_windows_virtual_key_id",
        "rate_limit_windows", "virtual_keys", ["virtual_key_id"], ["id"],
    )

    # --- usage_records: composite PK (virtual_key, year_month) ---
    op.add_column("usage_records", sa.Column("virtual_key_id", sa.Integer(), nullable=True))
    for row in conn.execute(sa.text("SELECT DISTINCT virtual_key FROM usage_records")):
        key_id = _lookup(row.virtual_key)
        if key_id is not None:
            conn.execute(
                sa.text(
                    "UPDATE usage_records SET virtual_key_id = :kid WHERE virtual_key = :vk"
                ),
                {"kid": key_id, "vk": row.virtual_key},
            )
    op.execute("DELETE FROM usage_records WHERE virtual_key_id IS NULL")
    op.drop_constraint("usage_records_pkey", "usage_records", type_="primary")
    op.drop_column("usage_records", "virtual_key")
    op.alter_column("usage_records", "virtual_key_id", nullable=False)
    op.create_primary_key(
        "pk_usage_records", "usage_records", ["virtual_key_id", "year_month"]
    )
    op.create_foreign_key(
        "fk_usage_records_virtual_key_id",
        "usage_records", "virtual_keys", ["virtual_key_id"], ["id"],
    )


def downgrade() -> None:
    # NOTE: raw plaintext cannot be recovered from key_hash (one-way by
    # design). This restores column *shapes* only; every restored
    # `virtual_key` string column is left NULL for self-serve-issued keys.
    # Re-run seed.py against data/seed_keys.json to repopulate the seeded
    # demo tenants' plaintext after downgrading.

    op.drop_constraint("fk_usage_records_virtual_key_id", "usage_records", type_="foreignkey")
    op.drop_constraint("pk_usage_records", "usage_records", type_="primary")
    op.add_column("usage_records", sa.Column("virtual_key", sa.String(), nullable=True))
    op.drop_column("usage_records", "virtual_key_id")
    op.alter_column("usage_records", "virtual_key", nullable=False)
    op.create_primary_key("usage_records_pkey", "usage_records", ["virtual_key", "year_month"])

    op.drop_constraint(
        "fk_rate_limit_windows_virtual_key_id", "rate_limit_windows", type_="foreignkey"
    )
    op.drop_constraint("pk_rate_limit_windows", "rate_limit_windows", type_="primary")
    op.add_column("rate_limit_windows", sa.Column("virtual_key", sa.String(), nullable=True))
    op.drop_column("rate_limit_windows", "virtual_key_id")
    op.alter_column("rate_limit_windows", "virtual_key", nullable=False)
    op.create_primary_key(
        "rate_limit_windows_pkey", "rate_limit_windows", ["virtual_key", "window_start"]
    )

    op.drop_index("ix_cache_entries_virtual_key_id", table_name="cache_entries")
    op.drop_constraint("fk_cache_entries_virtual_key_id", "cache_entries", type_="foreignkey")
    op.add_column("cache_entries", sa.Column("virtual_key", sa.String(), nullable=True))
    op.drop_column("cache_entries", "virtual_key_id")
    op.alter_column("cache_entries", "virtual_key", nullable=False)
    op.create_index("ix_cache_entries_virtual_key", "cache_entries", ["virtual_key"])

    op.drop_index("ix_request_logs_virtual_key_id", table_name="request_logs")
    op.drop_constraint("fk_request_logs_virtual_key_id", "request_logs", type_="foreignkey")
    op.add_column("request_logs", sa.Column("virtual_key", sa.String(), nullable=True))
    op.drop_column("request_logs", "virtual_key_id")
    op.alter_column("request_logs", "virtual_key", nullable=False)
    op.create_index("ix_request_logs_virtual_key", "request_logs", ["virtual_key"])

    op.drop_index("ix_virtual_keys_key_hash", table_name="virtual_keys")
    op.add_column("virtual_keys", sa.Column("virtual_key", sa.String(), nullable=True))
    op.drop_column("virtual_keys", "key_prefix")
    op.drop_column("virtual_keys", "key_hash")
    op.create_index("ix_virtual_keys_virtual_key", "virtual_keys", ["virtual_key"], unique=True)
